services:
  app_proxy:
    environment:
      APP_HOST: app
      APP_PORT: 3000

  app:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.2.2
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "18333:18333"
      - "18332:18332"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DEFAULT_CHAIN: test
      BITCOIND_EXTRA_ARGS: '-deprecatedrpc=create_bdb'
      APPS_SUBNET: "10.21.0.0/16"
      P2P_PORT: "18333"
      P2P_WHITEBIND_PORT: "8335"
      RPC_PORT: "18332"
      TOR_PORT: "8334"
      ZMQ_RAWBLOCK_PORT: "28332"
      ZMQ_RAWTX_PORT: "28333"
      ZMQ_HASHBLOCK_PORT: "28334"
      ZMQ_SEQUENCE_PORT: "28335"
      ZMQ_HASHTX_PORT: "28336"
      TOR_HOST: "127.0.0.1"
      TOR_SOCKS_PORT: "9050"
      TOR_CONTROL_PORT: "9051"
      TOR_CONTROL_PASSWORD: "moneyprintergobrrr"
      I2P_HOST: "127.0.0.1"
      I2P_SAM_PORT: "7656"
      BITCOIND_IP: "0.0.0.0"
      RPC_USER: "umbrel"
      RPC_PASS: "${APP_PASSWORD}"
      DEVICE_DOMAIN_NAME: "umbrel.local"
      P2P_HIDDEN_SERVICE: ""
      RPC_HIDDEN_SERVICE: ""
