services:
  app_proxy:
    environment:
      APP_HOST: signet_web
      APP_PORT: 80

  signet_web:
    image: nginx:alpine
    user: root
    restart: on-failure
    depends_on:
      - signet_server
    volumes:
      - ${APP_DATA_DIR}/banner.conf:/etc/nginx/conf.d/default.conf:ro

  signet_server:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.2.2
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "38333:38333"
      - "38332:38332"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DEFAULT_CHAIN: signet
      BITCOIND_EXTRA_ARGS: '-deprecatedrpc=create_bdb'
      APPS_SUBNET: "10.21.0.0/16"
      P2P_PORT: "38333"
      P2P_WHITEBIND_PORT: "8335"
      RPC_PORT: "38332"
      TOR_PORT: "8334"
      ZMQ_RAWBLOCK_PORT: "28332"
      ZMQ_RAWTX_PORT: "28333"
      ZMQ_HASHBLOCK_PORT: "28334"
      ZMQ_SEQUENCE_PORT: "28335"
      ZMQ_HASHTX_PORT: "28336"
      TOR_HOST: "127.0.0.1"
      TOR_SOCKS_PORT: "9050"
      TOR_CONTROL_PORT: "9051"
      TOR_CONTROL_PASSWORD: "moneyprintergobrrr"
      I2P_HOST: "127.0.0.1"
      I2P_SAM_PORT: "7656"
      BITCOIND_IP: "0.0.0.0"
      RPC_USER: "umbrel"
      RPC_PASS: "umbrel-electrs-shared-pass"
      DEVICE_DOMAIN_NAME: "umbrel.local"
      P2P_HIDDEN_SERVICE: ""
      RPC_HIDDEN_SERVICE: ""
