services:
  server:
    image: bitcoin/bitcoin:31.0
    restart: unless-stopped
    stop_grace_period: 5m
    ports:
      - "38333:38333"
      - "38332:38332"
    volumes:
      - ${APP_DATA_DIR}/data:/data/.bitcoin
    command:
      - -chain=signet
      - -datadir=/data/.bitcoin
      - -server=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=10.0.0.0/8
      - -rpcallowip=172.16.0.0/12
      - -rpcuser=umbrel
      - -rpcpassword=${APP_PASSWORD}
      - -rpcport=38332
      - -port=38333
